/*************************************************************************
 *
 *  HCL Technologies..... CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * Copyright 2020 HCL Technologies. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL Technologies.
 *
 *************************************************************************/
// Author : Generated by ADvantageCloud
// Revision History :

package com.awssupport.util;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

import com.amazonaws.auth.AWSCredentialsProvider;
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import com.amazonaws.services.eventbridge.AmazonEventBridge;
import com.amazonaws.services.eventbridge.AmazonEventBridgeClientBuilder;
import com.amazonaws.services.eventbridge.model.PutEventsRequest;
import com.amazonaws.services.eventbridge.model.PutEventsRequestEntry;
import com.amazonaws.services.eventbridge.model.PutEventsResult;
import com.amazonaws.services.eventbridge.model.PutEventsResultEntry;

public class AWSEventBusUtil {
	final static Logger logger = LogManager.getLogger(AWSEventBusUtil.class);

	public static void eventbus(String EVENT_DETAILS) throws IOException {

		try {
			logger.info("Inside AWS EventBus method");
			Properties prop = new Properties();
			InputStream awsinputStream = AWSEventBusUtil.class.getClassLoader()
					.getResourceAsStream("awscloudconfig.properties");
			prop.load(awsinputStream);

			AWSCredentialsProvider awsCredentials = new DefaultAWSCredentialsProviderChain();

			String DETAILTYPE = "Customer Transaction";
			String RESOURCE_ARN = prop.get("aws.eventbridge.arn").toString();
			String SOURCE = prop.get("aws.eventbridge.source").toString();
			String AWS_REGION = prop.get("aws.region").toString();
			String EVENT_BUS = prop.get("aws.eventbridge.eventbus").toString();

			logger.info("Parameters : " + "\nDETAILTYPE: " + DETAILTYPE + "\nRESOURCE_ARN: " + RESOURCE_ARN
					+ "\nSOURCE: " + SOURCE + "\nAWS_REGION: " + AWS_REGION + "\nEVENT_DETAILS: " + EVENT_DETAILS);

			final AmazonEventBridge eventBridge = AmazonEventBridgeClientBuilder.standard()
					.withCredentials(awsCredentials).withRegion(AWS_REGION).build();

			PutEventsRequestEntry request_entry = new PutEventsRequestEntry().withDetail(EVENT_DETAILS)
					.withDetailType(DETAILTYPE).withResources(RESOURCE_ARN).withEventBusName(EVENT_BUS)
					.withSource(SOURCE);

			PutEventsRequest request = new PutEventsRequest().withEntries(request_entry);

			PutEventsResult result = eventBridge.putEvents(request);

			for (PutEventsResultEntry resultEntry : result.getEntries()) {
				if (resultEntry.getEventId() != null) {
					logger.info("Event Id: " + resultEntry.getEventId());
					logger.info("Event ErrorMessage: " + resultEntry.getErrorMessage());
					logger.info("Notification sent through AWS Event Bridge.");
				} else {
					logger.info("Injection failed with Error Code: " + resultEntry.getErrorCode());
					logger.info("Failed to send AWS Event Bridge Notification.");
				}
			}
		} catch (Exception ex) {
			logger.error("Error in AWS Event Bus:" + ex);
		}
	}
}