/*************************************************************************
 *
 *  HCL Technologies..... CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * Copyright 2020 HCL Technologies. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL Technologies.
 *
 *************************************************************************/
// Author : Generated by ADvantageCloud
// Revision History :

package com.awssupport.util;

import java.io.IOException;
import java.io.InputStream;
import java.net.InetSocketAddress;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

import com.presto.banking.actionForm.Loan_Details;
import com.presto.banking.util.LoanCSVFileReader;

import net.spy.memcached.MemcachedClient;

public class AWSMemcached {
	private AWSMemcached() {
		throw new IllegalStateException("Utility class");
	}

	static final Logger logger = LogManager.getLogger(AWSMemcached.class);

	static MemcachedClient mcClient = null;

	private static MemcachedClient initiateConnection() throws IOException {
		try {
			Properties prop = new Properties();
			InputStream awsinputStream = AWSMemcached.class.getClassLoader()
					.getResourceAsStream("awscloudconfig.properties");
			prop.load(awsinputStream);

			// Connecting to Memcached server
			System.out.println("----------" + prop.get("aws.memcached.url").toString() + "-- - " +  Integer.parseInt(prop.get("aws.memcached.port").toString()));
			mcClient = new MemcachedClient(new InetSocketAddress(prop.get("aws.memcached.url").toString(), Integer.parseInt(prop.get("aws.memcached.port").toString())));
			
			logger.info("AWS Memcached Connected Sucessfully..!");
		} catch (Exception ex) {
			logger.error("Error in Clearing : " + ex);
		}
		return mcClient;


	}

	public static List<Loan_Details> getLoanDetails(String key) throws IOException {
		ArrayList<Loan_Details> loanresponse = null;
		try {
			initiateConnection();

			logger.info("Cache Key:" + key);
			if (mcClient.get(key) != null) {
				return (List<Loan_Details>) mcClient.get(key);
			}
			logger.info(new StringBuilder().append("Cache does not exists for Key ").append(key)
					.append(".\nAdding new...").toString());
			loanresponse = new LoanCSVFileReader().ReadCSV();
			mcClient.set("All", 900, loanresponse);
		} catch (NullPointerException npe) {
			logger.error("Error in GET Object from Cache");
		}
		return loanresponse;
	}

	public static void clearCache() {
		try {
			mcClient.flush();
		} catch (Exception ex) {
			logger.error("Error in Clearing : " + ex);
		}
	}
}