/*************************************************************************
 *
 *  HCL Technologies..... CONFIDENTIAL
 * _________________________________________________________________________________
 *
 * Copyright 2020 HCL Technologies. All rights reserved.
 *
 * NOTICE: All information contained herein is, and remains the property of HCL Technologies.
 *
 *************************************************************************/
// Author : Generated by ADvantageCloud
// Revision History :

package com.awssupport.util;

import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Properties;

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

import com.amazonaws.auth.AWSCredentialsProvider;
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain;
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.CreateQueueRequest;
import com.amazonaws.services.sqs.model.DeleteMessageRequest;
import com.amazonaws.services.sqs.model.ReceiveMessageRequest;
import com.amazonaws.services.sqs.model.SendMessageRequest;
import com.amazonaws.services.sqs.model.SendMessageResult;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;


public class AWSUtil implements Serializable {

	private static final long serialVersionUID = -5198666908856120180L;
	static Logger logger = LogManager.getLogger(AWSUtil.class);

	public  void sqsProducer(Object sqsObjects) {


		try {
		
		Properties awsCloudconfigProperties = new Properties();
		InputStream awsinputStream = getClass().getClassLoader().getResourceAsStream("awscloudconfig.properties");
		awsCloudconfigProperties.load(awsinputStream);

		AWSCredentialsProvider awsCredentials = new DefaultAWSCredentialsProviderChain();

		final AmazonSQS sqs = AmazonSQSClientBuilder.standard().withRegion(awsCloudconfigProperties.get("aws.region").toString())
				.withCredentials(awsCredentials).build();

		// Creating SQS Queue if not exists
		String queue_url = createsqs(awsCloudconfigProperties.get("aws.sqs.name").toString(), awsCloudconfigProperties.get("aws.region").toString());

			logger.info("Sending a message to Fifo Queue.\n");
			ArrayList ListOfsqsobject = (ArrayList) sqsObjects;

			Iterator ldIter = ListOfsqsobject.iterator();
			while (ldIter.hasNext()) {
				Object sqsObject = ldIter.next();
				Gson gson = new Gson();
				String gsonObj = gson.toJson(sqsObject);

				final SendMessageRequest sendMessageRequest = new SendMessageRequest(queue_url, gsonObj);

				sendMessageRequest.setMessageGroupId("messageGroup1");

				final SendMessageResult sendMessageResult = sqs.sendMessage(sendMessageRequest);
				final String sequenceNumber = sendMessageResult.getSequenceNumber();
				final String messageId = sendMessageResult.getMessageId();

				// logger.info("Send Message succeed with messageId " + messageId + ",
				// sequence number "
				// + sequenceNumber + "\n");
			}
			logger.info("");

		} catch (Exception ase) {
			logger.info(
					"Caught an Exception, which means " + "your request made it to Amazon SQS, but was "
							+ "rejected with an error response for some reason.");
			
		} 
	}


	public  void sqsConsumer(){

		Properties awsCloudconfigProperties = new Properties();
		InputStream awsinputStream = getClass().getClassLoader().getResourceAsStream("awscloudconfig.properties");
		try {
			awsCloudconfigProperties.load(awsinputStream);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		AWSCredentialsProvider awsCredentials = new DefaultAWSCredentialsProviderChain();

		final AmazonSQS sqs = AmazonSQSClientBuilder.standard().withRegion(awsCloudconfigProperties.get("aws.region").toString())
				.withCredentials(awsCredentials).build();

		String queue_url = createsqs(awsCloudconfigProperties.get("aws.sqs.name").toString(), awsCloudconfigProperties.get("aws.region").toString());

		logger.info("Receiving messages from MyFifoQueue.fifo.\n");
		final ReceiveMessageRequest receiveMessageRequest = new ReceiveMessageRequest(queue_url)
				.withMaxNumberOfMessages(10);

		final List<com.amazonaws.services.sqs.model.Message> messages = sqs.receiveMessage(receiveMessageRequest)
				.getMessages();

		logger.info(messages.toString());
		logger.info(messages.get(0).getBody());
		JsonParser parser = new JsonParser();
		JsonObject json = (JsonObject) parser.parse(messages.get(0).getBody());
		logger.info("===========================================================");
		logger.info("Name:				" + json.get("name"));
		logger.info("Loan Type:			" + json.get("loanType"));
		logger.info("Date:				" + json.get("date"));
		logger.info("Monthly Salary:		" + json.get("monthlySalary"));
		logger.info("Laon Amount:		" + json.get("loanAmount"));
		logger.info("isEligible:			" + json.get("isEligible"));
		logger.info("===========================================================");

		for (final com.amazonaws.services.sqs.model.Message message : messages) {
			logger.info("Message");
			logger.info("  MessageId:     " + message.getMessageId());
			logger.info("  ReceiptHandle: " + message.getReceiptHandle());
			logger.info("  MD5OfBody:     " + message.getMD5OfBody());
			logger.info("  Body:          " + message.getBody());
			for (final Entry<String, String> entry : message.getAttributes().entrySet()) {
				logger.info("Attribute");
				logger.info("  Name:  " + entry.getKey());
				logger.info("  Value: " + entry.getValue());
			}
			logger.info("Deleting the message...\n");
			final String messageReceiptHandle = message.getReceiptHandle();
			sqs.deleteMessage(new DeleteMessageRequest(queue_url, messageReceiptHandle));
		}
	}

	public  String createsqs(String queue_name, String region) {
		String queueUrl = "";
		AWSCredentialsProvider awsCredentials = new DefaultAWSCredentialsProviderChain();
		final AmazonSQS sqs = AmazonSQSClientBuilder.standard().withRegion(region).withCredentials(awsCredentials)
				.build();
		try {
			logger.info("Checking if SQS Queue exists...");
			String queue_url = sqs.getQueueUrl(queue_name).getQueueUrl();
			logger.info("SQS Queue Exists:" + queue_url);
			return queue_url;
		} catch (Exception sqsExp) {
			logger.info(sqsExp.getMessage());

			logger.info("\nCreating a new Amazon SQS FIFO queue called " + queue_name + "\n");

			final Map<String, String> attributes = new HashMap<String, String>();
			attributes.put("FifoQueue", "true");

			attributes.put("ContentBasedDeduplication", "true");

			final CreateQueueRequest createQueueRequest = new CreateQueueRequest(queue_name).withAttributes(attributes);
			queueUrl = sqs.createQueue(createQueueRequest).getQueueUrl();
			try {
				Thread.sleep(5000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			logger.info("Newly created SQS Queue Url : " + queueUrl);
		}
		return queueUrl;
	}
}